jlanzarotta/bufexplorer

doc/bufexplorer.txt
plugin/bufexplorer.vim

I added the following things to toggle the BufExplorer list on and off.
- the command `:ToggleBufExplorer`
- the map `<Leader>bt`, and 
- the function `ToggleBufExplorer()`
The function works by simply calling the `BufExplorer()` or `s:Close()` function, depending on the current state of BufExplorer. Now one can easily see which buffers are open (with a mapped function key, ideally), and then easily close the buffer list with the same key. 
I believe this pull request will satisfy the request in Issue #3.

Add toggle command

---

plugin/bufexplorer.vim

Revert Pull Request #15, which was intended to address an issue resulting from spurious SessionLoadPost events in Vim causing the MRU list to be reset.  The plan now is to leave the code as was but to alert users to the problem in the documentation.

Revert "bug fix"

---

doc/bufexplorer.txt

I noticed some missing spaces while reading `:help`:

Missing spaces, some typos

---

plugin/bufexplorer.vim

This pull request partially fixes issue #28. Instead of always calling ```BufExplorer()``` - to ensure the buffer list is active - before calling ```s:Close()```, I put a check in the ```ToggleBufExplorer()``` function, based on the active window's current buffer name.
This should greatly reduce the frequency of the bad behavior described in the issue, but it can still be made to happen if you jump through the right hoops. One such scenario is:
```
:BufExplorer<CR>
:BufExplorer<CR>
q
:BufExplorer<CR>
```
It is the ```execute "drop" name``` statement in ```BufExplorer()``` that appears to be the issue, causing the **[BufExplorer]** buffer to be marked as listed.

(Partially) Fixes: Erroneous listing of [BufExplorer] in buffer list

---

.gitignore
plugin/bufexplorer.vim

This fixes bug introduced in pull request #29. 
Remove ```s:BufExplorerName()``` function, and use ```s:name``` instead. The function was causing ```:ToggleBufExplorer()``` to fail on non-Windows boxes.

Fix :ToggleBufExplorer on non-Windows boxes

---

plugin/bufexplorer.vim

I found that vim-surround's `ds` keybinding was causing bufexplorer to have a 1/2 second delay when deleting buffers. It was waiting for the `s` to be pressed so wouldn't type the `d`.
I've added `<nowait>` to all the commands in the Bufexplorer window to get around these types of collisions.
For more details:
https://github.com/tpope/vim-surround/issues/98#issuecomment-77435471
Thanks for a great plugin! I've been using it since the early days, maybe 13 years ago :smile:

Add <nowait> to all the commands to stop any delays from other bindings

---

plugin/bufexplorer.vim

Fixes #39...
If BufExplorer's MRUList is empty or has no listed buffers in it, create
an array of listed buffers from vim's buffer list instead.
Tested on console versions only:
* Windows, vim 7.4
* Mac OSX, neovim 0.1.1

Add secondary check for listed buffers when closing.

---

plugin/bufexplorer.vim

Previous changes to Close() to make it more tab-friendly did not correctly handle the following scenario:
- :tabe
- \be
- q
Expected result is to show an empty buffer, actual result was to show last-used buffer from previous tab

Fix quit in empty tab

---

plugin/bufexplorer.vim

This PR has the same intention as #56, but is backward compatible with versions of Vim that do not support $tab. 
The problem is that "$tab" was introduced in 7.4.2237 as an alternative to 999tab. At some point, 999tab stop working.

Backward-compatible fix for invalid tab range bug

---

README.md

Fix installation command for Plug and NeoBundle as `bufexpolerer.vim` pointed to a private repository.

Fix installation commands

---

plugin/bufexplorer.vim

Setting g:bufexplorer_version_warn to zero disables the version warnings
and silently disables the plugin.

Add option to hide version mismatch warnings

---

plugin/bufexplorer.vim

Currently there is no option to force buffer deletion. This patch adds dialog which will ask user to confirm deletion if buffer has unsaved data and will call bd! or bw! if user confirms.

Add confirmation dialog to handle deletion of buffer with unsaved changes

---

plugin/bufexplorer.vim

It's a useful feature to be able to delete all buffers.  It's very
convenient to delete buffers from within BufExplorer, but it's annoying
to be unable to delete the final buffer without exiting BufExplorer and
deleting the final buffer via ``:bwipeout`` or similar.
It's also difficult to accurately track buffers in ``s:MRUList`` under
all circumstances.  For example, after starting Vim and restoring a
session created with the ``:mksession`` command, buffers are added using
:badd, which BufExplorer currently doesn't track.  Attempting to delete
any of these buffers would previously fail with the message "Sorry, you
are not allowed to delete the last buffer".  To replicate this:
vim one two three
:mksession session.vim
:qa
vim
:source session.vim
BufExplorer is already equipped to handle …

Allow deletion of last buffer.

---

plugin/bufexplorer.vim

I found when using bufexplorer to switch a new buffer, a "[bufexplorer]" item will appear in the jumplist, and when jumping through ctrl-o and ctrl-i, will enter a blank screen. So I use ":keepjumps" to disable this annoying behavior.

delete [bufexplorer] appeared in jumplist

---

plugin/bufexplorer.vim

If you use either split mode, you can no longer use the regular non-split mode. This is because the split mode set s:splitMode and that variable is never reset to "" to allow you run without split mode.
This change simply resets s:splitMode to "" after completing the split mode bufexplorer.

Reset splitMode

---

plugin/bufexplorer.vim

If vim was started in read-only mode (`vim -R`), then opening bufexplorer triggers an error:
```
Error detected while processing function BufExplorer[49]..<SNR>49_DisplayBufferList:
line   16:W10: Warning: Changing a readonly file
```

fix error when vim is in read-only mode

---

plugin/bufexplorer.vim

Since commit 4f20377, s:splitMode != '' no longer implies that a split was triggered, so
we need to track that fact with a different variable.

Use independent variable to track window splitting

---

plugin/bufexplorer.vim

Loading a session which includes hidden or unloaded buffers breaks the
MRUList sort order in BufExplorer, because only the visible buffers are
added to the MRUList and the MRUCmp() function doesn't deal with buffer
numbers not found in the MRUList, which causes visible buffers included
in the MRUList to be listed after other buffers not yet in the MRUList.
Fix this by simply resetting the MRUList after loading a session so all
listed buffers are included.
To allow for wiping out buffers when switching between sessions, which
is done by sessionman.vim and possibly other plugins and scripts, also
filter MRUList when resetting to exclude buffers that no longer exist.

Fix MRU sort order after loading vim session

---

plugin/bufexplorer.vim

wipe explorer buffer on hide

---

README.md
doc/bufexplorer.txt
plugin/bufexplorer.vim

Thanks for you plugin, I've used this plugin for many years, but currently I met an annoying problem, I'm running jobs in terminal emulators, which were supported by Vim (since version 8.1) and Neovim. And the default behivor of bufexplorer will print all the buffers, including the terminal buffers, eg:
I don't want the bufexplorer to show the terminal buffers by default, so I added this option to show it or not.

feat: add option g:bufExplorerShowTerminal to show terminal buffers or not

---

plugin/bufexplorer.vim

This pull request addresses a few issues surrounding buffer sort order and buffer name displaying.  The initial motivation for these changes was to ensure that files and directories below a common directory would sort near each other when using the `fullpath` sort order.  With `fullpath`, the ordering should depend only on each buffer's full path name; historically, however, sorting has been a best-effort function of the displayed strings in the BufExplorer window, leading to some anomalies.
- Sorting by `fullname` now depends only on the buffer's absolute path using a new sorting mechanism. Other sort modes have been converted to use this mechanism as well.
- Display of directory buffers is now suppressed when `g:bufExplorerShowDirectories == 0` as described in the BufExplorer …

Fix buffer sorting and display issues

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

This pull request provides a new MRU buffer tracking algorithm to:
- Fix issue #8 "Bufexplorer MRU sort doesn't work properly if using restore_session.vim".
- Fix issue #87 "Bufexplorer interferes with the startinsert! command".
- Treat unlisted buffers as least-recently-used instead of most-recently-used in the MRU sort order.
- Remove the now-unneeded status indicator "One tab/buffer" in the BufExplorer status line; also remove the associated undocumented variable `g:bufExplorerOnlyOneTab`.
- Replace the undocumented `m` key (intended for debugging MRU logic) with the `BufExplorer_eval()` and `BufExplorer_execute()` general debugging features.
- Improve speed of MRU tracking.
- For demonstration purposes, create a temporary directory for testing and create a few test files:
```
mkdir …
```

Improve buffer MRU tracking algorithm

---

plugin/bufexplorer.vim

- Allow deletion/wiping of Neovim terminal buffers (addresses #69).
- Retain buffer until it has been fully wiped.
- Improve error message when deleting an unlisted buffer.
BufExplorer's `d` and `D` commands delete and wipe buffers, respectively, using `:bdelete` and `:bwipe`.  Deleting a buffer makes it unlisted (but still in existence).  Wiping a buffer removes it completely from existence.
For normal buffers, these operations require `!` to force removal when the buffer has been modified.  BufExplorer checks `&modified` to determine when to use `!`.
For terminal buffers, both `:bdelete` and `:bwipe` require `!` to force removal. On Vim, terminal buffers appear to be modified (so `&modified == 1`); however, Neovim terminal buffers have `&modified == 0`, so BufExplorer was not previously …

Buffer removal enhancements

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

- Improve the display of terminal buffers to be a uniform `/current/working/directory/!PID:shellName` on Vim and Neovim.
- Enable the ability to toggle the showing of terminal buffers (via the `X` command).
On Neovim, terminal buffers are named as:
```
term://WorkingDirectoryAtTerminalLaunch//PID:shellPath
```
On Vim, the name contains only a `!` and the shell path:
```
!/path/to/shell
```
In order to sort by `fullpath` in a more useful manner, synthesize a path for terminal buffers based on the shell's current working directory.  Display the shell's name without leading path for brevity.  Terminal buffers are now displayed with this format:
```
/current/working/directory/!PID:shellName
```
At present, the current working directory of the shell can be determined only on Unix-like systems …

Improve terminal buffer display and toggling ability

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

- Provide a mechanism for users to adjust BufExplorer command mappings.  This addresses #73 and #113.
- Expose new "forced" delete and wipe actions that may be optionally mapped by the user.  This removes confirmation for modified buffers and terminal buffers.
- Remove incomplete visual-mode `d`/`D` mappings.
BufExplorer uses buffer-local mappings for its commands (e.g., `<Enter>` to open a buffer, `q` to quit BufExplorer, etc.).  These mappings are now exposed via Vim's `<Plug>` mechanism such that users may add, remove, or otherwise adjust command mappings.
Buffer-local mappings must be adjusted only after the BufExplorer buffer has been created.  To notify the user of this event, BufExplorer now sends a `User` autocommand named `BufExplorer_Started` once the BufExplorer buffer has been …

Allow customized mappings

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

- Add new `O` command to open the buffer under the cursor into the window where BufExplorer was originally launched.
- This addresses issue #55.
When launching BufExplorer via `:BufExplorer`, the original launch window is reused temporarily for BufExplorer; then, when pressing `<Enter>` to select a buffer, BufExplorer closes and the original launch window is used for the selected buffer.
But when launching BufExplorer via `:BufExplorerHorizontalSplit` or `:BufExplorerVerticalSplit`, a new split is created for BufExplorer.  If `<Enter>` is used to select a buffer, this buffer will be opened in the split created for BufExplorer.
This new `O` command provides a way to first close the split that was created for BufExplorer at launch such that the selected buffer will be opened in the original …

Add `O` command to open in the original window at BufExplorer launch.

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

This pull request modifies lines that are adjacent to lines modified in pull request https://github.com/jlanzarotta/bufexplorer/pull/128, which leads to a small merge conflict; therefore, I've based this pull request on #128 instead of on 7.9.0 to make merging easier in the event that both requests are accepted.  If changes are required to either pull request, I'm happy to make necessary adjustments and rebase accordingly to ensure smooth merging.
- Add `action` argument to `:BufExplorer` and `:ToggleBufExplorer` commands for flexible control of BufExplorer window opening and closing:
- Switch to a running BufExplorer window even if GUI support is not available.
- Close BufExplorer even if running in a different window.
- Toggle BufExplorer window with flexible split modes.
- Make default …

Flexibly open, close, and toggle BufExplorer windows and splits

---

plugin/bufexplorer.vim

When no help text is displayed and there are no buffers to display, the BufExplorer buffer is logically empty; however, Vim does not make it easy to work with completely empty buffers.  For example, `line('$')` returns the last line number in the buffer, which in general is the same as the number of lines in the buffer; but for a completely empty buffer, `line('$')` returns one instead of the expected value of zero.  This is because Vim needs to leave room for the cursor to exist on some line number, even for an empty buffer.  Also, the function `getline(startLineNbr, endLineNbr)` returns a list of the lines in the inclusive range `[startLineNbr, endLineNbr]`, and correctly returns an empty list when `endLineNbr < startLineNbr`; however, the shortcut invocation `getline(startLineNbr, …

Fix #131 by handling the case of a completely empty buffer.

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

- Addresses issue #114.
- The new variable `g:bufExplorerColumns` holds a customizable list of column strings that dictate the columns in the buffer listing.
- Predefined column string values for `g:bufExplorerColumns`:
```
number
indicators
numberindicators
line
rawpath
name
fullpath
fulldir
homerelpath
homereldir
relativepath
relativedir
path
dir
splittablepath
icon
```
- The new function `BufExplorer_redisplay()` causes BufExplorer to redisplay the buffer list according to the columns defined by `g:bufExplorerColumns`.
- The new event `BufExplorer_PreDisplay` will be sent before each update to the buffer listing, enabling last-minute adjustments to the columns.
- Setting `g:bufExplorerColumns` is sufficient to choose any subset of the predefined columns, e.g.:
```vim
" Show only the …
```

Allow customization of buffer listing columns

---

plugin/bufexplorer.vim

Fix regression in splitting behavior.
- Restore BufExplorer window-splitting logic.
- When BufExplorer closes via `q`, ensure the original window-at-launch is chosen regardless of split mode.
This fixes a window-splitting regression I introduced in BufExplorer 7.10.0.
Symptom: Opening BufExplorer in a split above/below/right/left when the window at launch is not topmost/bottommost/rightmost/leftmost, respectively, causes BufExplorer to open a split window at the extreme topmost/bottommost/rightmost/leftmost position instead of a position next to the window at launch.  In addition, when closing BufExplorer, instead of focusing the original window at launch, it incorrectly focuses the window adjacent to the extreme window that held BufExplorer; then, the original buffer from launch will be …

Fix regression in splitting behavior.

---

doc/bufexplorer.txt
plugin/bufexplorer.vim

With "No Name" buffers displayed via `g:bufExplorerShowNoName = 1`, BufExplorer can fail to return to the original buffer when `q` is pressed.  For example:
- Start Vim.
- Show "No Name" buffers via `:let g:bufExplorerShowNoName = 1`.
- Insert some text via `ihello<Escape>`.
- Launch BufExplorer via `\be`.
- Notice Buffer 1 is displayed as `[No Name]`.
- Quit BufExplorer with `q`.
- Notice a new (empty) buffer is now displayed, e.g.: `:ls`
1  h + "[No Name]"                    line 1
3 %a   "[No Name]"                    line 1
BufExplorer fails to return to the original buffer because it has been ignoring "No Name" buffers for the purposes of MRU tracking.  The MRU system tracks buffers in most-recently-used order, but it does not track buffers where `s:ShouldIgnore()` returns true. …

Stop ignoring "No Name" buffers in MRU tracking.
